export const UPDATE_PETS = "UPDATE_PETS";

export const ADD_TO_BOOKED = "ADD_TO_BOOKED";
export const ADD_MULTIPLE_TO_BOOKED = "ADD_MULTIPLE_TO_BOOKED";
export const REMOVE_FROM_BOOKED = "REMOVE_FROM_BOOKED";
export const CLEAR_BOOKED = "CLEAR_BOOKED";
export const UPDATE_BOOKED_QUANTITY = "UPDATE_BOOKED_QUANTITY";
export const TOGGLE_BOOKED = "TOGGLE_BOOKED";

export const UPDATE_PETTYPES = "UPDATE_PETTYPES";
export const UPDATE_CURRENT_PETTYPE = "UPDATE_CURRENT_PETTYPE";
